#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

foamCleanCase
rm -f log*
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

runApplication blockMesh 
runApplication $application

runApplication touch result.foam

#------------------------------------------------------------------------------
